config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#index", as: :root

  get "/books", to: "books#index", as: :books
  get "/movies", to: "movies#index", as: :movies
  get "/albums", to: "albums#index", as: :albums

  get "/books/new", to: "books#new", as: :new_book
  get "/movies/new", to: "movies#new", as: :new_movie
  get "/albums/new", to: "albums#new", as: :new_album

  post "/books", to: "books#create", as: :create_book
  post "/movies", to: "movies#create", as: :create_movie
  post "/albums", to: "albums#create", as: :create_albums

  get "/books/:id", to: "books#show", as: :book
  get "/movies/:id", to: "movies#show", as: :movie
  get "/albums/:id", to: "albums#show", as: :album

  patch "/books/:id", to: "books#update", as: :update_book
  patch "/movies/:id", to: "movies#update", as: :update_movie
  patch "/albums/:id", to: "albums#update", as: :update_album

  get "/books/:id/edit", to: "books#edit", as: :edit_book
  get "/movies/:id/edit", to: "movies#edit", as: :edit_movie
  get "/albums/:id/edit", to: "albums#edit", as: :edit_album

  delete "/books/:id/delete", to: "books#destroy", as: :delete_book
  delete "/movies/:id/delete", to: "movies#destroy", as: :delete_movie
  delete "/albums/:id/delete", to: "albums#destroy", as: :delete_album

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all.sort_by{|album| -album.rank }
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if params[:album][:upvote]
      @album.rank += 1
    end
    if @album.update(params.require(:album).permit(:title, :artist, :description))
      redirect_to album_path(@album.id)
    else
      render :new
    end
  end

  def new
    @album = Album.new #why do this??? ask.
  end

  def create
    @album = Album.new(params.require(:album).permit(:title, :artist, :description))
    @album.rank = 0
    if @album.save
      redirect_to albums_path
    else
      render :new
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all.sort_by {|book| -book.rank}
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if params[:book][:upvote]
      @book.rank +=1
    end
    if @book.update(params.require(:book).permit(:title, :price, :description))
      redirect_to book_path(@book.id)
    else
      render :new
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params.require(:book).permit(:title, :description, :author))
    @book.rank = 0
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.all.sort_by { |movie| -movie.rank }
    @albums = Album.all.sort_by { |album| -album.rank }
    @books = Book.all.sort_by { |book| -book.rank}
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all.sort_by {|movie| -movie.rank}
  end

  def new
    @movie = Movie.new
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if params[:movie][:upvote]
      @movie.rank += 1
    end
    if @movie.update(params.require(:movie).permit(:title, :description, :director))
      redirect_to movie_path(@movie.id)
    else
      render :new
    end
  end

  def create
    @movie = Movie.new(params.require(:movie).permit(:title, :description, :director))
    @movie.rank = 0
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/albums/_albumform.html.erb
<%= form_for @album do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit "Submit", class: "btn btn-default" %>
<% end %>

app/views/albums/edit.html.erb
<div class="container adjust-left">
  <h2>Edit <%= @album.title %></h2>

  <%= render "albumform" %>
</div>

app/views/albums/index.html.erb
<div class="container adjust-left">

  <h2>Albums</h2>
  <table>
    <tbody>

      <tr>
        <th>
          Ranking
        </th>
        <th>
          Name
        </th>
        <th>
          Upvote
        </th>
      </tr>

      <% @albums.each do |m| %>
      <tr>
        <td>
          Ranked: <%= m.rank %>
        </td>
        <td>
          <%= link_to m.title, album_path(m.id) %>
        </td>
        <td>
          <%= button_to "Upvote", update_album_path(m.id), params:{'album[upvote]' => true}, method: :patch, :class => 'vote btn btn-default'%>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>


  <%= link_to "View All Media", root_path, class: "btn btn-default"%>
  <%= link_to "Create New Album", new_album_path, class: "btn btn-default" %>

</div>

app/views/albums/new.html.erb
<div class="container adjust-left">
  <h2>Add a new Album</h2>

  <%= render "albumform" %>
</div>

app/views/albums/show.html.erb
<div class="container show-page">
  <h2><%= @album.title %></h2>
  <h4>Ranking: <%= @album.rank %></h4>
  <h3>Artist: <%= @album.artist %></h3>
  <%= @album.description %>

  <%= button_to "Upvote", update_album_path(@album.id), params:{'album[upvote]' => true}, method: :patch, class: "btn btn-default show-nav vote"%>
  <hr>
  <%= link_to "Edit #{@album.title}", edit_album_path(@album.id), class: "btn btn-default show-nav editing" %>
  <%= link_to "Delete", delete_album_path(@album.id), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-default show-nav deletion' %>
  <%= link_to "View all media", root_path, class: 'btn btn-default show-nav' %>
  <%= link_to "View all albums", albums_path, class: 'btn btn-default show-nav' %>
</div>

app/views/all_media/_rankings.html.erb
<% media ||= @movies %>
<% media ||= @books %>

<table>
  <tbody>

    <tr>
      <th>
        Ranking
      </th>
      <th>
        Name
      </th>
      <th>
        Upvote
      </th>
    </tr>

    <% media.each do |m| %>
    <tr>
      <td>
        Ranked: <%= m.rank %>
      </td>
      <td>
        <%= m.title %>
      </td>
      <td>
        <%#= button_to "Upvote", action: "update[:id]" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_bookform.html.erb
<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :description  %>
  <%= f.text_area :description %>

  <%= f.submit "Submit", class: "btn btn-default" %>
<% end %>

app/views/books/edit.html.erb
<div class="container adjust-left">
  <h2>Edit <%= @book.title %></h2>
  <%= render "bookform" %>
</div>

app/views/books/index.html.erb
<div class="container adjust-left">
  <h2>Books</h2>
  <table>
    <tbody>

      <tr>
        <th>
          Ranking
        </th>
        <th>
          Name
        </th>
        <th>
          Upvote
        </th>
      </tr>

      <% @books.each do |m| %>
      <tr>
        <td>
          Ranked: <%= m.rank %>
        </td>
        <td>
          <%= link_to m.title, book_path(m.id) %>
        </td>
        <td>
          <%= button_to "Upvote", update_book_path(m.id), params:{'book[upvote]' => true }, method: :patch, class: "btn btn-default vote"%>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "View All Media", root_path, class: "btn btn-default"%>
  <%= link_to "Create New Book", new_book_path, class: "btn btn-default" %>

</div>

app/views/books/new.html.erb
<div class="container adjust-left">
  <h2>Add a book</h2>

  <%= render "bookform" %>
</div>

app/views/books/show.html.erb
<div class="container show-page">
  <h2><%= @book.title %></h2>
  <h4>Ranking: <%= @book.rank %></h4>
  <h3>Author: <%= @book.author %></h3>
  <%= @book.description %>

  <%= button_to "Upvote", update_book_path(@book.id), params:{'book[upvote]' => true }, method: :patch, class: "btn btn-default vote"%>
  <hr>
  <%= link_to "Edit #{@book.title}", edit_book_path(@book.id), class: "btn btn-default show-nav editing"%>
  <%= link_to "Delete", delete_book_path(@book.id), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-default show-nav deletion' %>
  <%= link_to "View all media", root_path, class: 'btn btn-default show-nav' %>
  <%= link_to "View all books", books_path, class: 'btn btn-default show-nav' %>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="movies col-sm-4"> <!-- The movies column -->
    <div class="icon glyphicon glyphicon-film"></div>
    <h1>Top Movies</h1>
    <%@movies.each do |movie| %>
    <div class="media-block">
      <h2><%= link_to movie.title, movie_path(movie.id) %></h2>
      Ranked: <%= movie.rank %>
    </div>
    <% end %>
    <br>   <!-- Note: get rid of this br -->
    <%= link_to "view more movies", movies_path %>
  </div>

  <div class="books col-sm-4"> <!-- The book column -->
    <div class="icon glyphicon glyphicon-book"></div>
    <h1>Top Books</h1>
      <% @books.each do |book| %>
      <div class="media-block">
        <h2><%= link_to book.title, book_path(book.id) %></h2>
        Ranked: <%= book.rank %>
      </div>
    <% end %>
    <br>
    <%= link_to "view more books", books_path %>
  </div>

  <div class="albums col-sm-4"> <!-- The album column -->
    <div class="icon glyphicon glyphicon-music"></div>
    <h1>Top Albums</h1>
    <% @albums.each do |album| %>
    <div class="media-block">
      <h2><%= link_to album.title, album_path(album.id) %></h2>
      Ranked <%= album.rank %>
    </div>
    <% end %>
    <br>
    <%= link_to "view more albums", albums_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediaRanker</title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <header> <!--the header -->
    <div class="logo container">
      <h1><%= link_to "Media Ranker", root_path %></h1>
      <h2>Ranking the best of everything</h2>
    </div>
  </header> <!--the end of header -->

<%= yield %>

</body>
</html>

app/views/movies/_movieform.html.erb
<%= form_for @movie do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :director %>
  <%= f.text_field :director %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit "Submit", class: "btn btn-default" %>
<% end %>

app/views/movies/edit.html.erb
<h2>Edit <%= @movie.title %></h2>
<%= render "movieform" %>

app/views/movies/index.html.erb
<div class="container adjust-left">
  <h2>Movies</h2>
  <table>
    <tbody>
      <tr>
        <th>
          Ranking
        </th>
        <th>
          Name
        </th>
        <th>
          Upvote
        </th>
      </tr>

      <% @movies.each do |m| %>
      <tr>
        <td>
          Ranked: <%= m.rank %>
        </td>
        <td>
          <%= link_to m.title, movie_path(m.id) %>
        </td>
        <td>
          <%= button_to "Upvote", update_movie_path(m.id), params:{'movie[upvote]' => true},method: :patch, class: "btn btn-default vote"%>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "View All Media", root_path, class: "btn btn-default"%>
  <%= link_to "Create New Movie", new_movie_path, class: "btn btn-default" %>

</div>

app/views/movies/new.html.erb
<h2>Add a movie</h2>

<%= render "movieform" %>

app/views/movies/show.html.erb
<div class="container show-page">
  <h2><%= @movie.title %></h2>
  <h4>Ranking: <%= @movie.rank %></h4>
  <h3>Director: <%= @movie.director %></h3>
  <%= @movie.description %>
  <%= button_to "Upvote", update_movie_path(@movie.id), params:{'movie[upvote]' => true}, method: :patch, class: "btn btn-default vote"%>
  <hr>
  <%= link_to "Edit #{@movie.title}", edit_movie_path(@movie.id), class: "btn btn-default show-nav editing"%>
  <%= link_to "Delete", delete_movie_path(@movie.id), method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-default show-nav deletion' %>
  <%= link_to "View all media", root_path, class: 'btn btn-default show-nav' %>
  <%= link_to "View all moveis", movies_path, class: 'btn btn-default show-nav' %>
</div>